name: NiftyChat
version: 1.2.9
website: https://netcoding.net/
author: Brian Graham

main: net.netcoding.niftychat.NiftyChat
depend: [NiftyBukkit, NiftyRanks]

commands:
  censor:
    description: Manage chat censoring
    usage: /<command> <add|edit|remove|list> <badword> [replace]
  format:
    description: Manage chat formatting
    usage: /<command> <group|format|prefix|suffix|message> <rank> [value]
  list:
    description: Show all, specific or current servers with player counts and names
    usage: /<command>
    aliases: [glist, online, gonline]
  message:
    description: Send a message to another player
    usage: /<command> <player> <message>
    aliases: [msg, whisper, tell, shout, reply, m, w, t, s, r]
  mute:
    description: Mute player from chat
    usage: /<command> <player> [time] [server]
    aliases: [unmute, globalmute, globalunmute, gmute, gunmute]
  nick:
    description: Sets player nickname
    usage: /<command> <<nick|clear>|<player> <nick|clear|revoke|grant>>
  realname:
    description: Find a players realname by nickname
    usage: /<command> <nick>
    aliases: rn
  socialspy:
    description: Spy on private messages from players
    usage: /<command> <player> [server]
    aliases: [spy, unsocialspy, unspy, globalsocialspy, globalspy, gsocialspy, gspy, globalunsocialspy, globalunspy, gunsocialspy, gunspy]
  vanish:
    description: Vanish from other players
    usage: /<command> <player> [server]
    aliases: [unvanish, globalvanish, globalunvanish, gvanish, gunvanish, gv, gunv, v, unv]
  whois:
    description: Shows information about a given player
    usage: /<command> <player>
    aliases: [who, what, whoadmin, whoisadmin, whatadmin]

permissions:
  niftychat.*:
    description: Gives access to all plugin features and commands
    children:
      niftychat.censor.*:
        description: Allows you to access all censor features
        children:
          niftychat.censor:
            description: Allows you to modify the censor
          niftychat.censor.list:
            description: Allows you to list censored words
          niftychat.censor.manage:
            description: Allows you to add, edit and remove censored words
      niftychat.chat.*:
        description: Allows you to bypass all chat restrictions
        children:
          niftychat.chat:
            description: Allows you to chat
          niftychat.chat.bypass.*:
            description: Allows you to bypass all chat filtering
            children:
              niftychat.chat.bypass.advertise:
                description: Allows you to put IP addresses and websites with ports in chat
              niftychat.chat.bypass.caps:
                description: Allows you to use CAPS in chat
              niftychat.chat.bypass.censor:
                description: Allows you to bypass the badword censor in chat
              niftychat.chat.bypass.move:
                description: Allows you to chat without moving on first join
              niftychat.chat.bypass.repeat:
                description: Allows you to submit the same message in chat
              niftychat.chat.bypass.url:
                description: Allows you to put websites without ports in chat
          niftychat.chat.color:
            description: Allows you to use colors in chat
          niftychat.chat.format:
            description: Allows you to use formatting in chat
          niftychat.chat.magic:
            description: Allows you to use magic in chat
      niftychat.format.*:
        description: Allows you to access all format features
        children:
          niftychat.format:
            description: Allows you to edit chat formats
          niftychat.format.edit:
            description: Allows you to edit rank format, prefix, suffix and message
          niftychat.format.manage:
            description: Allows you to create and delete rank formats
          niftychat.format.view:
            description: Allows you to view rank format, prefix and suffix
      niftychat.message.*:
        description: Allows you to access all message features
        children:
          niftychat.message:
            description: Allows you to send private messages players
          niftychat.message.bypass.*:
            description: Allows you to bypass all private chat filtering
            children:
              niftychat.message.bypass.advertise:
                description: Allows you to put IP addresses and websites with ports in private chat
              niftychat.message.bypass.caps:
                description: Allows you to use CAPS in private chat
              niftychat.message.bypass.censor:
                description: Allows you to bypass the badword censor in private chat
              niftychat.message.bypass.move:
                description: Allows you to private chat without moving on first join
              niftychat.message.bypass.repeat:
                description: Allows you to submit the same message in private chat
              niftychat.message.bypass.url:
                description: Allows you to put websites without ports in private chat
          niftychat.message.color:
            description: Allows you to use colors in private chat
          niftychat.message.format:
            description: Allows you to use formatting in private chat
          niftychat.message.global:
            description: Allows you to send private messages to players across servers
          niftychat.message.magic:
            description: Allows you to use magic in private chat
      niftychat.mute.*:
        description: Allows you to access to all mute features
        children:
          niftychat.mute:
            description: Allows you to mute players
          niftychat.mute.global:
            description: Allows you to globally mute players
      niftychat.nick.*:
        description: Allows you to access all nicknames features
        children:
          niftychat.nick:
            description: Allows you to set your nickname
          niftychat.nick.clear:
            description: Allows you to clear player nicknames
          niftychat.nick.grant:
            description: Allows you to restore player access to changing their nick
          niftychat.nick.revoke:
            description: Allows you to revoke player access to changing their nick
          niftychat.nick.other:
            description: Allows you to set the nicknames of other players
          niftychat.nick.color:
            description: Allows you to set nicknames with colors
          niftychat.nick.magic:
            description: Allows you to set nicknames with magic
          niftychat.nick.format:
            description: Allows you to set nicknames with formatting
      niftychat.realname:
        description: Allows you to find a players realname by nickname
      niftychat.socialspy.*:
        description: Allows you to access all socialspy features
        children:
          niftychat.socialspy:
            description: Allows you to run the socialspy command
          niftychat.socialspy.global:
            description: Allows you to globally spy on players private messages
      niftychat.vanish.*:
        description: Allows you to access all vanish features
        children:
          niftychat.vanish:
            description: Allows you to run the vanish command
          niftychat.vanish.global:
            description: Allows you to vanish from all servers
          niftychat.vanish.others:
            description: Allows you to vanish other players
          niftychat.vanish.see:
            description: Allows you to see vanished players