name: NiftyChat
version: 1.0
website: http://netcoding.net/
author: Brian Graham

main: net.netcoding.niftychat.NiftyChat
depend: [NiftyBukkit, NiftyRanks]
softdepend: [Vault]

commands:
  censor:
    description: Manage chat censoring
    usage: /<command> <add|edit|remove|list> <badword> [replace]
    aliases: cl
  format:
    description: Manage chat formatting
    usage: /<command> <rank> <prefix|suffix|format> [value]
#  mute:
#    description: Mute player from chat
#    permission: niftychat.chat.mute
#    usage: /<command> <player> [time]
  nick:
    description: Sets player nickname
    usage: /<command> <<nick|clear>|<player> <nick|clear|revoke|grant>>
  realname:
    description: Find a players realname by nickname
    usage: /<command> <nick>
    aliases: rn

permissions:
  niftychat.*:
    description: Gives access to all plugin features and commands
    children:
      niftychat.censor.*:
        description: Allows you to run all censor commands
        children:
          niftychat.censor.list:
            description: Allows you to list censored words
          niftychat.censor.manage:
            description: Allows you to add, edit and remove censored words
      niftychat.chat.*:
        description: Allows you to bypass all chat restrictions
        children:
          niftychat.chat.bypass.*:
            description: Allows you to bypass all chat filtering
            children:
              niftychat.chat.bypass.advertise:
                description: Allows you to put IP addresses and websites with ports in chat
              niftychat.chat.bypass.caps:
                description: Allows you to use CAPS in chat
              niftychat.chat.bypass.censor:
                description: Allows you to bypass the badword censor in chat
              niftychat.chat.bypass.move:
                description: Allows you to talk without moving on first join
              niftychat.chat.bypass.repeat:
                description: Allows you to submit the same message in chat
              niftychat.chat.bypass.url:
                description: Allows you to put websites without ports in chat
          niftychat.chat.color:
            description: Allows you to use colors in chat
          niftychat.chat.format:
            description: Allows you to use formatting in chat
          niftychat.chat.magic:
            description: Allows you to use magic in chat
      niftychat.format.*:
        description: Allows you to run all format commands
        children:
          niftychat.format.manage:
            description: Allows you to edit rank format, prefix and suffix
          niftychat.format.view:
            description: Allows you to view rank format, prefix and suffix
      niftychat.join.fullserver:
        description: Allows you to join the server even when it is full
      niftychat.nick.*:
        description: Allows you to access all nicknames features and commands
        children:
          niftychat.nick:
            description: Allows you to set your nickname
          niftychat.nick.clear:
            description: Allows you to clear player nicknames
          niftychat.nick.revoke:
            description: Allows you to revoke or grant player access to the nick command
          niftychat.nick.other:
            description: Allows you to set the nicknames of other players
          niftychat.nick.color:
            description: Allows you to set nicknames with colors
          niftychat.nick.magic:
            description: Allows you to set nicknames with magic
          niftychat.nick.format:
            description: Allows you to set nicknames with formatting
      niftychat.realname:
        description: Allows you to find a players realname by nickname